---
title: "Gesammelte EUR2 Münzen"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

## Libraries
library(tidyverse)

## Externe Daten ----
source("rd_celex.r", local = knitr::knit_global())       #celex
source("rd_collection.r", local = knitr::knit_global())  #collection
source("rd_circulation.r", local = knitr::knit_global()) #circulation
```

<style type="text/css">
h1.title {
  font-size: 22px;
  color: DarkGreen;
}
</style>

```{r data, echo=FALSE}
df <- Reduce(function(...) merge(..., by = "ID", all.x = TRUE, no.dups = TRUE),
             list(coins, collection |> select(ID, Qualität, Ablage), circulation)) |> 
  as_tibble() |> 
  filter(!is.na(Ablage)) |> # nur noch nicht gesammelte
  transmute(Jahr = Prägejahr,
            Land,
            Mzz = abbreviate(Münzzeichen, 7), 
            Motiv = case_when(nchar(Abbildung) > 70 ~ paste0(str_sub(Abbildung, 1, 70), "..."),
                             TRUE ~ Abbildung),
            Qualität, Hfgkt) |> 
  mutate(Qualität = case_when(Qualität == 0 ~ "(0) ★★★", # Geschütztes Leerzeichen (Alt + 0160)
                              Qualität == 1 ~ "(1) ☆★★",
                              Qualität == 2 ~ "(2) ☆☆★",
                              Qualität == 3 ~ "(3) ☆☆☆"),
         Hfgkt = c("▼", "▽", "▢", "△", "▲")[Hfgkt]) |>
  arrange(Jahr, Land, Motiv, Mzz) |> 
  group_by(Jahr)
```

```{r table}
gt::gt(df, id = "coin_coll") |> 
  gt::data_color(columns = "Qualität", target_columns = everything(),
                 palette = "YlGn", alpha = .5, reverse = TRUE, method = "factor",
                 contrast_algo = "wcag") |>  
  gt::cols_align(align = "right", columns = "Mzz") |> 
  gt::cols_align(align = "center", columns = "Hfgkt") |> 
  gt::tab_options(table.font.size = 11,
                  row_group.background.color = "grey45",
                  row_group.font.weight = "bold",
                  row_group.padding = 2,
                  data_row.padding = 1)
```

